// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLOWHS_Q8zXXf1TiU2OE1agm_Jml8DGE',
    appId: '1:534134901611:web:47e7df4cfdb32ff5289a2e',
    messagingSenderId: '534134901611',
    projectId: 'totoki-7c2dd',
    authDomain: 'totoki-7c2dd.firebaseapp.com',
    storageBucket: 'totoki-7c2dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFLDuXeYawO3MrvQJu5JLxzoQle2QYao',
    appId: '1:534134901611:android:f82e864ecd5a21dc289a2e',
    messagingSenderId: '534134901611',
    projectId: 'totoki-7c2dd',
    storageBucket: 'totoki-7c2dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcCWKV6oS0aAzOISp5nH-0yODvmLB8zbk',
    appId: '1:534134901611:ios:80b1ec644c52c7a6289a2e',
    messagingSenderId: '534134901611',
    projectId: 'totoki-7c2dd',
    storageBucket: 'totoki-7c2dd.firebasestorage.app',
    iosBundleId: 'com.example.totoki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcCWKV6oS0aAzOISp5nH-0yODvmLB8zbk',
    appId: '1:534134901611:ios:80b1ec644c52c7a6289a2e',
    messagingSenderId: '534134901611',
    projectId: 'totoki-7c2dd',
    storageBucket: 'totoki-7c2dd.firebasestorage.app',
    iosBundleId: 'com.example.totoki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdLOWHS_Q8zXXf1TiU2OE1agm_Jml8DGE',
    appId: '1:534134901611:web:a756a5413485b78f289a2e',
    messagingSenderId: '534134901611',
    projectId: 'totoki-7c2dd',
    authDomain: 'totoki-7c2dd.firebaseapp.com',
    storageBucket: 'totoki-7c2dd.firebasestorage.app',
  );
}
