import 'package:flutter/material.dart';
import 'package:mygame/components/Menu/flashcard/business/Flashcard.dart';
import 'package:mygame/components/Menu/flashcard/data/database_helper_io_impl.dart';
class Achievementnoti extends ChangeNotifier{
  static final _dbhelper = DatabaseHelper.instance;
  List<Flashcard> _card=[];
  List<Flashcard> exampleList=[
    Flashcard(
      deckId: 1,
      word: "apple",
      meaning: "a type of fruit",
      example: "I ate an apple this morning.",
      ipa: "/ˈæp.əl/",
      id: null,
      createdAt: null,
      updatedAt: null,
      img: null,
      synonyms: null,
      sound: null,
      defSound: null,
      usageSound: null,
      complexity: 1,
      interval: null,
      reps: 0,
      due: null,
      lastReview: null,
      lapses: null,
      easeFactor: null,
    ),
    Flashcard(
      deckId: 1,
      word: "run",
      meaning: "move fast by foot",
      example: "He runs every morning.",
      ipa: "/rʌn/",
      id: null,
      createdAt: null,
      updatedAt: null,
      img: null,
      synonyms: null,
      sound: null,
      defSound: null,
      usageSound: null,
      complexity: 2,
      interval: null,
      reps: 1,
      due: null,
      lastReview: null,
      lapses: null,
      easeFactor: null,
    ),
    Flashcard(
      deckId: 1,
      word: "book",
      meaning: "a written or printed work",
      example: "She likes reading books.",
      ipa: "/bʊk/",
      id: null,
      createdAt: null,
      updatedAt: null,
      img: null,
      synonyms: null,
      sound: null,
      defSound: null,
      usageSound: null,
      complexity: 3,
      interval: null,
      reps: 2,
      due: null,
      lastReview: null,
      lapses: null,
      easeFactor: null,
    ),
    Flashcard(
      deckId: 1,
      word: "happy",
      meaning: "feeling or showing pleasure",
      example: "I’m happy today.",
      ipa: "/ˈhæp.i/",
      id: null,
      createdAt: null,
      updatedAt: null,
      img: null,
      synonyms: null,
      sound: null,
      defSound: null,
      usageSound: null,
      complexity: 4,
      interval: null,
      reps: 3,
      due: null,
      lastReview: null,
      lapses: null,
      easeFactor: null,
    ),
    Flashcard(
      deckId: 1,
      word: "blue",
      meaning: "a color",
      example: "The sky is blue.",
      ipa: "/bluː/",
      id: null,
      createdAt: null,
      updatedAt: null,
      img: null,
      synonyms: null,
      sound: null,
      defSound: null,
      usageSound: null,
      complexity: 5,
      interval: null,
      reps: 4,
      due: null,
      lastReview: null,
      lapses: null,
      easeFactor: null,
    ),
    Flashcard(
      deckId: 1,
      word: "strong",
      meaning: "having power",
      example: "He is very strong.",
      ipa: "/strɒŋ/",
      id: null,
      createdAt: null,
      updatedAt: null,
      img: null,
      synonyms: null,
      sound: null,
      defSound: null,
      usageSound: null,
      complexity: 6,
      interval: null,
      reps: 5,
      due: null,
      lastReview: null,
      lapses: null,
      easeFactor: null,
    ),
    Flashcard(
      deckId: 1,
      word: "music",
      meaning: "organized sound",
      example: "She listens to music every day.",
      ipa: "/ˈmjuː.zɪk/",
      id: null,
      createdAt: null,
      updatedAt: null,
      img: null,
      synonyms: null,
      sound: null,
      defSound: null,
      usageSound: null,
      complexity: 7,
      interval: null,
      reps: 6,
      due: null,
      lastReview: null,
      lapses: null,
      easeFactor: null,
    ),
  ];
  bool isLoading=false;
  Future<void> fetchCard()async{
    isLoading=true;
    notifyListeners();
    final data=await _dbhelper.getAllCard();
    _card.clear();
    _card.addAll(exampleList);
    _card.addAll(data);
    isLoading=false;
    notifyListeners();
  }
  List<Flashcard> getCard()
  {
    if(_card.isEmpty){
      fetchCard();
    }
    return _card; 
  }
}